config/routes.rb
Lucybrown::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	resources :works, path: 'work'
	resources :clients, path: 'client'
  
  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'


  root 'static_pages#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/work.rb
class Work < ActiveRecord::Base

	validates :title, presence: true
	validates :content, presence: true

	before_save :remove_photo

# Image 1
	has_attached_file :image1, styles: {large: "525x420#",
																			medium: "300x260#",
																			small: "300x180#",
																			full: "525x"
	}


	validates_attachment_content_type :image1, :content_type => /\Aimage\/.*\z/



# Image 2
	has_attached_file :image2, styles: {large: "525x420#",
																			medium: "300x260#",
																			small: "300x180#"
	}


	validates_attachment_content_type :image2, :content_type => /\Aimage\/.*\z/


	def previous
  Work.where(["id < ?", id]).last
	end

	def next
	  Work.where(["id > ?", id]).first
	end


	def remove_photo
		self.image2_file_name = nil if self.destroyImage2 == true
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	def index

		@client = Work.where(category: "Client").order('created_at DESC')
		@worksa = @client[0..14]
		@worksb = @client[14..28]
		@worksc = @client[28..42]
		@worksd = @client[42..56]

			if @worksa
				@worksa_total = @worksa.count
			end

			if @worksb	
				@worksb_total = @worksb.count
			end

			if @worksc
				@worksc_total = @worksc.count
			end

			if @worksd
				@worksd_total = @worksd.count
			end
		
	end


	def show
		@work = Work.find(params[:id])
		
	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		@works = Work.order('created_at DESC')
		
		@work1 = @works[0]
		@work2 = @works[1]
		@work3 = @works[2]

		@b = StaticPage.last
		@content = @b.homecontact
	end


	def about
		@b = StaticPage.last
		@content = @b.about
	end


	def contact
		@b = StaticPage.last
		@content = @b.contact
	end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController



	def index
		#@posts = Work.order('created_at DESC')

		#@works1 = @posts[0..14]
		#@works2 = @posts[14..28]
		#@works3 = @posts[28..42]
		#@works4 = @posts[42..56]
	
		@personal = Work.where(category: "Personal").order('created_at DESC')
		@works1 = @personal[0..14]
		@works2 = @personal[14..28]
		@works3 = @personal[28..42]
		@works4 = @personal[42..56]
		
			if @works1
				@works1_total = @works1.count
			end

			if @works2	
				@works2_total = @works2.count
			end

			if @works3
				@works3_total = @works3.count
			end

			if @works4
				@works4_total = @works4.count
			end

	end




	def show
		@work = Work.find(params[:id])
		
	end


	def new
		@work = Work.new
	end


	def create
		@work = Work.new(work_params)

		@work.save

		redirect_to root_path
	end


	def edit
		@work = Work.find(params[:id])
	end


	def update
		@work = Work.find(params[:id])
		@work.update(work_params)

		redirect_to root_path
	end


	def destroy
		@work = Work.find(params[:id])
		@work.destroy
		redirect_to root_path
	end





	def work_params
		params.require(:work).permit(:title, :content, :image1, :image2, :destroyImage2, :category)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/clients/index.html.erb
<% @page = "work" %>
<% @subpage = "client" %>


<!-- Client Work -->

<div class="work_index_box">

	<h2 class="category <%= "active" if @subpage == "personal" %>"><%= link_to "Personal Work", works_path %></h2>
	<h2 class="category <%= "active" if @subpage == "client" %>"><%= link_to "Client Work", clients_path %></h2>

	<% if @worksa %>
		<div class="work_index_occurance <%= 'three' if @worksa_total >= 1 && @worksa_total <= 3 %><%= 'six' if @worksa_total >= 4 && @worksa_total <= 6 %><%= 'nine' if @worksa_total >= 7 && @worksa_total <= 9 %><%= 'eleven' if @worksa_total >= 10 && @worksa_total <= 11 %><%= 'fourteen' if @worksa_total >= 12 && @worksa_total <= 15 %>">
		
			

				<% @b = Hash[@worksa.map.with_index.to_a] %>

				<% @worksa.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>


	<!-- 2nd instance -->
	<% if @worksb %>
		<div class="work_index_occurance <%= 'three' if @worksb_total >= 1 && @worksb_total <= 3 %><%= 'six' if @worksb_total >= 4 && @worksb_total <= 6 %><%= 'nine' if @worksb_total >= 7 && @worksb_total <= 9 %><%= 'eleven' if @worksb_total >= 10 && @worksb_total <= 11 %><%= 'fourteen' if @worksb_total >= 12 && @worksb_total <= 15 %>">
		
			

				<% @b = Hash[@worksb.map.with_index.to_a] %>

				<% @worksb.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>




	<!-- 3rd instance -->
	<% if @worksc %>
		<div class="work_index_occurance <%= 'three' if @worksc_total >= 1 && @worksc_total <= 3 %><%= 'six' if @worksc_total >= 4 && @worksc_total <= 6 %><%= 'nine' if @worksc_total >= 7 && @worksc_total <= 9 %><%= 'eleven' if @worksc_total >= 10 && @worksc_total <= 11 %><%= 'fourteen' if @worksc_total >= 12 && @worksc_total <= 15 %>">
		
			

				<% @b = Hash[@worksc.map.with_index.to_a] %>

				<% @worksc.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>




	<!-- 4th instance -->
	<% if @worksd %>
		<div class="work_index_occurance <%= 'three' if @worksd_total >= 1 && @worksd_total <= 3 %><%= 'six' if @worksd_total >= 4 && @worksd_total <= 6 %><%= 'nine' if @worksd_total >= 7 && @worksd_total <= 9 %><%= 'eleven' if @worksd_total >= 10 && @worksd_total <= 11 %><%= 'fourteen' if @worksd_total >= 12 && @worksd_total <= 15 %>">
		
			

				<% @b = Hash[@worksd.map.with_index.to_a] %>

				<% @worksd.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>




</div>

<!-- End of Client work -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="Lucy Brown is a graphic designer, educator and researcher, with a ceaseless love for typography" />
    <meta name="keywords" content="graphic design, Manchester, art, typography, education, design, graphic designer, freelance graphic designer, typographer, graphic design lecturer, graphic design research, graphic arts, letters, letterforms, graphic designer north west"  />

    <title><%= content_for?(:title) ? yield(:title) : "Lucy Brown" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="wrapper">

    <div class="centered">
      <!-- HEADER -->
      <header>

            <div class="navbox">
              <div class="navcontent">
                <ul>
                
                <% if @page == "work" %>
                  <li class="navcorrectpage"><%= link_to 'WORK', works_path %></li>
                <% else %>
                  <li><%= link_to 'WORK', works_path %></li>
                <% end %>

                <% if @page == "about" %>
                  <li class="navcorrectpage"><%= link_to 'ABOUT', about_path %></li>
                <% else %>
                  <li><%= link_to 'ABOUT', about_path %></li>
                <% end %>

                <% if @page == "contact" %>
                  <li class="navcorrectpage"><%= link_to 'CONTACT', contact_path %></li>
                <% else %>
                  <li><%= link_to 'CONTACT', contact_path %></li>
                <% end %>

                </ul>
              </div>
            </div>
        

            <div class="sitetitle">
              <h1><%= link_to 'Lucy Brown', root_path %> <span class="strapline">graphic design, education, research</span></h1>
            </div>
          
      </header>
      <!-- HEADER end -->
      


      <!-- PAGE -->
      <section class="pagecontent">
        

          <%= yield %>

        
      </section>
      <!-- PAGE end -->


    </div>
  </div>
  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% @page = "about" %>


<div class="staticpage">

	<%= raw @content %>

</div>

app/views/static_pages/contact.html.erb
<% @page = "contact" %>

<div class="staticpage">
	<div class="contactdetails">
		<%= raw @content %>
	</div>
</div>

app/views/static_pages/home.html.erb
<% @page = "home" %>

	<div class="home_images">
		
		<div class="i home_image0">
			<% if @work1 %>
				<%= link_to (image_tag @work1.image1(:medium)), works_path %>
			<% end %>
		</div>

		<div class="i home_image1">
			<% if @work2 %>
				<%= link_to (image_tag @work2.image1(:small)), works_path %>
			<% end %>	
		</div>

		<div class="i home_image2">
			<% if @work3 %>
				<%= link_to (image_tag @work3.image1(:large)), works_path %>
			<% end %>
		</div>	

	</div>
	



<div class="homecontact">
	<%= raw @content %>
</div>

app/views/works/index.html.erb
<% @page = "work" %>
<% @subpage = "personal" %>


<!-- Personal Work -->

<div class="work_index_box">

	<h2 class="category <%= "active" if @subpage == "personal" %>"><%= link_to "Personal Work", works_path %></h2>
	<h2 class="category <%= "active" if @subpage == "client" %>"><%= link_to "Client Work", clients_path %></h2>

	<% if @works1 %>
		<div class="work_index_occurance <%= 'three' if @works1_total >= 1 && @works1_total <= 3 %><%= 'six' if @works1_total >= 4 && @works1_total <= 6 %><%= 'nine' if @works1_total >= 7 && @works1_total <= 9 %><%= 'eleven' if @works1_total >= 10 && @works1_total <= 11 %><%= 'fourteen' if @works1_total >= 12 && @works1_total <= 15 %>">
		
			

				<% @b = Hash[@works1.map.with_index.to_a] %>

				<% @works1.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>


	<!-- 2nd instance -->
	<% if @works2 %>
		<div class="work_index_occurance <%= 'three' if @works2_total >= 1 && @works2_total <= 3 %><%= 'six' if @works2_total >= 4 && @works2_total <= 6 %><%= 'nine' if @works2_total >= 7 && @works2_total <= 9 %><%= 'eleven' if @works2_total >= 10 && @works2_total <= 11 %><%= 'fourteen' if @works2_total >= 12 && @works2_total <= 15 %>">
		
			

				<% @b = Hash[@works2.map.with_index.to_a] %>

				<% @works2.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>




	<!-- 3rd instance -->
	<% if @works3 %>
		<div class="work_index_occurance <%= 'three' if @works3_total >= 1 && @works3_total <= 3 %><%= 'six' if @works3_total >= 4 && @works3_total <= 6 %><%= 'nine' if @works3_total >= 7 && @works3_total <= 9 %><%= 'eleven' if @works3_total >= 10 && @works3_total <= 11 %><%= 'fourteen' if @works3_total >= 12 && @works3_total <= 15 %>">
		
			

				<% @b = Hash[@works3.map.with_index.to_a] %>

				<% @works3.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>




	<!-- 4th instance -->
	<% if @works4 %>
		<div class="work_index_occurance <%= 'three' if @works4_total >= 1 && @works4_total <= 3 %><%= 'six' if @works4_total >= 4 && @works4_total <= 6 %><%= 'nine' if @works4_total >= 7 && @works4_total <= 9 %><%= 'eleven' if @works4_total >= 10 && @works4_total <= 11 %><%= 'fourteen' if @works4_total >= 12 && @works4_total <= 15 %>">
		
			

				<% @b = Hash[@works4.map.with_index.to_a] %>

				<% @works4.each do |work| %>

						
						<% if [1, 4, 7, 8, 12].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:small)), work_path(work) %>
							</div>
						<% end %>


						<% if  [0, 5, 6, 9, 13].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:medium)), work_path(work) %>
							</div>
						<% end %>

					
						<% if [2, 3, 10, 11].include? @b[work] %>
							<div class="i index_image<%= @b[work] %>">
									<%= link_to (image_tag work.image1(:large)), work_path(work) %>
							</div>
						<% end %>

				<% end %>

		</div>
	<% end %>


</div>

<!-- End of Personal work -->

app/views/works/show.html.erb
	<div class="work_show_box">

		<div class="work_show_right">
			<h3><%= @work.title %></h3>

			<% if @work.previous %>
				<p class="show_next shownav"><%= link_to "NEXT", @work.previous %></p>
			<% end %>
<!--
			<% if @work.next %>
				<p class="show_next shownav"><%= link_to "NEXT", @work.next %></p>
			<% end %>
-->
			<div class="show_images">
				<% if @work.image2.exists? %>
					<div class="show_image2"><%= image_tag @work.image2(:small) %></div>
				<% end %>

				<% if @work.image1.exists? %>
					<div class="show_image1"><%= image_tag @work.image1(:full) %></div>
				<% end %>	
			</div>
			
			<div class="show_content">
				<p><%= raw @work.content %></p>
			</div>
		</div>

		<div class="work_show_left">
		<!--
			<% if @work.previous %>
				<p class="show_back shownav"><%= link_to "BACK", @work.previous %></p>
			<% end %>
		-->
			<% if @work.next %>
				<p class="show_back shownav"><%= link_to "BACK", @work.next %></p>
			<% end %>

		</div>	
	</div>